name: Build, Run, and Test ROS Melodic Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_EMAIL }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Build Docker image
      run: docker build -t ros-melodic-container .

    - name: Run tests inside Docker container
      run: |
        docker run ros-melodic-container /bin/bash -c "
  /root/catkin_ws/spawn_headless.sh &  # Start Gazebo and the Trajectory Controller in the background
  PID1=\$!                             # Store the PID of the background process
  sleep 15                             # Wait for 15 seconds to properly start
  /root/catkin_ws/start_tests.sh          # Run our unit tests now
  kill \$PID1                          # Terminate the first command
  wait \$PID1                          # Wait for the first command to terminate properly
"
      continue-on-error: true
